### ISSUE TITLE
Running node-export-server on AWS Lambda

### ISSUE THREAD

**Issue by pamelafox** [highcharts/node-export-server#42]
We are attempting to run this from AWS Lambda. 

However, it runs into an EPIPE exception.  Here are the logs:
  * attaching exit listeners to the process..
  * Pool started: 
maxWorkers: 1 
initialWorkers: 1 
workLimit: 60 
  * listening to process exit: true
  * phantom 1 - spawning worker
  * starting export
  * attempting to export from raw input
  * phantom - received work, finding available worker
  * phantom - found available worker
  * phantom 1 - starting work
  * Error: write EPIPE
at Object.exports._errnoException (util.js:870:11)
at exports._exceptionWithHostPort (util.js:893:20)
at WriteWrap.afterWrite (net.js:763:14)
  * terminating, killing all running phantom processes

Your README specifically mentions Beanstalk as a way to run this. Do you know why the EPIPE exception happens on Lambda, and if it is possible to run it there?

If not, then we will put it on Beanstalk. Thank you!

**Comment by pamelafox** [comment]
I have now put it on Beanstalk and it seems to work.

FYI to others putting it on BeanStalk: I wasn't able to get the permissions to work for npm install, so I had to use an ebextension file to chown the relevant directory.

I put a file named 00_postdeployscript.config in .ebextensions in my project folder:
```
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/99_fix_node_permissions.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      chown -R nodejs:nodejs /tmp/deployment/*

```

I also specified the ACCEPT_HIGHCHARTS_LICENSE environment variable under Configuration -> Software Configuration.
